### ISSUE TITLE
Auto-compile stops for unknown reason

### ISSUE THREAD

**Issue by tripptuttle** [jrief/django-sass-processor#137] opened 2020-03-13 17:26 UTC
First, this package has been a life saver! Thank you. 

About 6 months ago, auto-compiling when a template is rendered totally stopped for me. I eventually had to completely delete and re-start a new Pipenv virtual environment to get it working. 

Now, the same issue has happened again, there were no package upgrades and errors are never thrown, I only realized it by looking at the CSS being loaded by my browser through my local runserver instance. All works and CSS compiled and updated if I manually run `./manage.py compilescss` but that sort of defeats the purpose. 

I tried trashing my environment and rebuilding, ensure I had the current `libsass` on my machine and `libsass-python`, `django-compressor`, and `django-sass-processor`. I also have deleted all the locally stored static files and started over. 

Has anyone else run into this? 

When loading a template, here are the signals being sent - does django-sass rely on any of them to trigger libsass? 

![Screen Shot 2020-03-13 at 13 23 17](https://user-images.githubusercontent.com/8353629/76644644-cfa74100-652d-11ea-9939-00340860b05f.png)

Please let me know if there is somewhere else I should be looking for troubleshooting, I'm used to an exception being thrown in the template if anything isn't working as it should, and  

Thanks for any advice!

**Comment by jrief** [comment] 2020-03-13 19:06
I'm closing this, because it is a unreproducible error.

**Closed by jrief** 2020-03-13 19:06 UTC

**Comment by tripptuttle** [comment] 2020-03-13 21:22
Just FYI in case it is helpful to others, it seems `compressor` was disabled within the Django settings by a collaborator on this project, which caused `SassProcessor.__call__` method to never fire. This didn't throw any exceptions, just failed silently. I see the checks to ensure libsass `sass` package is installed, but didn't see any checks for `compressor` being included in Django's `INSTALLED_APPS` setting.
