### ISSUE TITLE
Error loading template: 'crispy_forms_tags' is not a registered tag library

### ISSUE THREAD

**Issue by franksmit** [jrief/django-sass-processor#29] opened 2016-02-24 14:55 UTC
Hi,

I'm sorry for the issue title. I couldn't think of a better title.

I get the following error message when running `./manage.py compilescss`:

```
Invalid template [...]/venv/local/lib/python2.7/site-packages/rest_framework/
templates/rest_framework/filters/django_filter_crispyforms.html: 
'crispy_forms_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
bootstrap3
cache
compress
future
i18n
l10n
log
rest_framework
sass_tags
static
staticfiles
tz
```

The application uses Django REST framework, but not django-crispy-forms (it's an optional dependency). I figured out that django-sass-processor loads all templates to look for `sass_src` tags ([sass_processor/management/commands/compilescss.py#L85](https://github.com/jrief/django-sass-processor/blob/master/sass_processor/management/commands/compilescss.py#L85)). This means mean the django-crispy-forms templates included with Django REST framework also get loaded even if we're not using them.

After thinking for a while I thought a template blacklist would be a good solution. What do you think about it?

Thanks,
Frank

**Comment by jrief** [comment] 2016-02-24 21:33
Then presumably in one of your templates you are using a templatetag named ``crispy_forms_tags ``.

If its so, please close.

**Comment by bxm156** [comment] 2016-02-24 22:40
I had the same problem too, the django rest framework includes templates that perhaps use it, even though my project never used them.

**Comment by jrief** [comment] 2016-02-24 23:09
which version of DRF? I currently using 3.1.3 and do not encounter these problems.

**Comment by mjonker-embed** [comment] 2016-02-25 07:20
We (including @franksmit) use the following:
```
Django==1.9.2
django-sass-processor==0.3.4
djangorestframework==3.3.2
libsass==0.10.1
```

**Comment by jrief** [comment] 2016-02-25 08:33
ok
In DRF 3.1.3 the templatetag crispy_forms_tags is not used. This seems to haven been added later to the file
rest_framework/templates/rest_framework/filters/django_filter_crispyforms.html

So what can we do?

* you add crispyforms to your project
* someone adds an option, say ``--ignore-template-errors`` to the command compilescss 

the latter approach is presumably the more future-proof

**Comment by mjonker-embed** [comment] 2016-02-25 08:34
I'd say the latter as well

**Comment by jrief** [comment] 2016-02-25 09:13
Just a question, from looking at the code there should only be an error message. The compilation step should not abort. Or is this different in your environment?

**Comment by mjonker-embed** [comment] 2016-02-25 09:14
It still works indeed. It's just not very pretty :wink:

**Comment by jrief** [comment] 2016-02-25 11:38
I just added a check on the verbosity. If its 0 no warnings are generated.
Please checkout from GitHub and test, it then will be part of 0.3.5

**Comment by mjonker-embed** [comment] 2016-02-25 12:27
Yay works great!

**Comment by dszmaj** [comment] 2016-10-18 23:24
@jrief exactly this breaks my sass routine, when crispy-forms are added to my project it just works

unfortunately not as intended... 'sass_src' pointing to scss in static folder serves just precompiled css, if that css is deleted it doesn't compile on runtime, SASS_PROCESSOR_ENABLED is set to DEBUG value (True), SASS_PROCESSOR_AUTO_INCLUDE = False, no other settings, manage command works good after crispy forms addition

django 1.9
python 3.5

**Closed** 2017-02-06 07:45 UTC
